// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sistemarcas.Infrastructure.Context;

namespace _4Sistemarcas.Infrastructure.Migrations
{
    [DbContext(typeof(SistemarcasContext))]
    [Migration("20220820130404_processoexterno")]
    partial class processoexterno
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Sistemarcas.Domain.Models.Anexos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<short>("Categoriaanexoid")
                        .HasColumnType("smallint");

                    b.Property<int>("Clienteid")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Data")
                        .HasColumnType("time");

                    b.Property<int>("Despachodetalheid")
                        .HasColumnType("int");

                    b.Property<int>("Despachoid")
                        .HasColumnType("int");

                    b.Property<int>("Empresaid")
                        .HasColumnType("int");

                    b.Property<int>("Estudo_viabilidade_id")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Pedidoid")
                        .HasColumnType("int");

                    b.Property<int>("Processoid")
                        .HasColumnType("int");

                    b.Property<int>("Processopeticaoid")
                        .HasColumnType("int");

                    b.Property<int>("Tarefaid")
                        .HasColumnType("int");

                    b.Property<int>("Usuario_criador_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Anexos");
                });

            modelBuilder.Entity("Sistemarcas.Domain.Models.Cargos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Cargos");
                });

            modelBuilder.Entity("Sistemarcas.Domain.Models.Cidades", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Area")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Codigo_ibge")
                        .HasColumnType("int");

                    b.Property<decimal>("Densidade_demo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Estadoid")
                        .HasColumnType("int");

                    b.Property<string>("Gentilico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Populacao_2010")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Estadoid");

                    b.ToTable("Cidades");
                });

            modelBuilder.Entity("Sistemarcas.Domain.Models.Classes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<short>("Tipo")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("Sistemarcas.Domain.Models.Classes_Itens", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Classe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Classeid")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numerobase")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Classeid");

                    b.ToTable("Classes_Itens");
                });

            modelBuilder.Entity("Sistemarcas.Domain.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bairro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Celular")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Cidadeid")
                        .HasColumnType("int");

                    b.Property<string>("Cnpj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Complemento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cpf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Datanascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Documentoprofissional")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Endereco")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("Estadocivilid")
                        .HasColumnType("smallint");

                    b.Property<bool>("Internacional")
                        .HasColumnType("bit");

                    b.Property<string>("Nacionalidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naturalidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("Numero")
                        .HasColumnType("smallint");

                    b.Property<bool>("Pre_cadastro")
                        .HasColumnType("bit");

                    b.Property<bool>("Primeiroacessoportal")
                        .HasColumnType("bit");

                    b.Property<string>("Profissao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senhaportal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sexo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Sistemarcas.Domain.Models.ClientesEmpresas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cargoid")
                        .HasColumnType("int");

                    b.Property<int>("Clienteid")
                        .HasColumnType("int");

                    b.Property<int>("Empresaid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Cargoid");

                    b.HasIndex("Clienteid");

                    b.HasIndex("Empresaid");

                    b.ToTable("ClientesEmpresas");
                });

            modelBuilder.Entity("Sistemarcas.Domain.Models.Cnaes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cnaes");
                });

            modelBuilder.Entity("Sistemarcas.Domain.Models.Contas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Clienteid")
                        .HasColumnType("int");

                    b.Property<int>("Convenioid")
                        .HasColumnType("int");

                    b.Property<decimal>("Desconto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Empresaid")
                        .HasColumnType("int");

                    b.Property<short>("Numeroparcelas")
                        .HasColumnType("smallint");

                    b.Property<int>("Pessoa_vendedor_id")
                        .HasColumnType("int");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Valorpermuta")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Vendedorid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Contas");
                });

            modelBuilder.Entity("Sistemarcas.Domain.Models.Contas_Parcelas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Contaid")
                        .HasColumnType("int");

                    b.Property<DateTime>("Datavencimento")
                        .HasColumnType("datetime2");

                    b.Property<int>("Formapagamentoid")
                        .HasColumnType("int");

                    b.Property<short>("Numeroparcela")
                        .HasColumnType("smallint");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Contas_Parcelas");
                });

            modelBuilder.Entity("Sistemarcas.Domain.Models.Convenios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Desconto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Empresaid")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Convenios");
                });

            modelBuilder.Entity("Sistemarcas.Domain.Models.Correspondentes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Pessoa_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Pessoa_id");

                    b.ToTable("Correspondentes");
                });

            modelBuilder.Entity("Sistemarcas.Domain.Models.CustosIndividuais", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("CustosIndividuais");
                });

            modelBuilder.Entity("Sistemarcas.Domain.Models.Despachos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<TimeSpan>("Datarevista")
                        .HasColumnType("time");

                    b.Property<string>("Numerorevista")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Despachos");
                });

            modelBuilder.Entity("Sistemarcas.Domain.Models.Despachos_Detalhes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Datainclusao")
                        .HasColumnType("datetime2");

                    b.Property<int>("Despachoid")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fimprazoextraordinario")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Fimprazoordinario")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Inicioprazoextraordinario")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Inicioprazoordinario")
                        .HasColumnType("datetime2");

                    b.Property<int>("Processoid")
                        .HasColumnType("int");

                    b.Property<string>("Texto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tipodespachoid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Despachoid");

                    b.HasIndex("Processoid");

                    b.HasIndex("Tipodespachoid");

                    b.ToTable("Despachos_Detalhes");
                });

            modelBuilder.Entity("Sistemarcas.Domain.Models.Empresas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bairro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Cidadeid")
                        .HasColumnType("int");

                    b.Property<string>("Cnpj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Complemento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Endenreco")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Endereco")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fantasia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inscricaoestadual")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Porteanvisaid")
                        .HasColumnType("int");

                    b.Property<int>("Porteinpiid")
                        .HasColumnType("int");

                    b.Property<int>("Portepoliciaid")
                        .HasColumnType("int");

                    b.Property<bool>("Pre_cadastro")
                        .HasColumnType("bit");

                    b.Property<string>("Razaosocial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Responsavel_legal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("Sistemarcas.Domain.Models.Empresas_Classes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Classeitemid")
                        .HasColumnType("int");

                    b.Property<int>("Empresaid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Classeitemid");

                    b.HasIndex("Empresaid");

                    b.ToTable("Empresas_Classes");
                });

            modelBuilder.Entity("Sistemarcas.Domain.Models.Empresas_Cnaes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cnaeid")
                        .HasColumnType("int");

                    b.Property<int>("Empresaid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Cnaeid");

                    b.HasIndex("Empresaid");

                    b.ToTable("Empresas_Cnaes");
                });

            modelBuilder.Entity("Sistemarcas.Domain.Models.Estados", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Paisid")
                        .HasColumnType("int");

                    b.Property<string>("Sigla")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Paisid");

                    b.ToTable("Estados");
                });

            modelBuilder.Entity("Sistemarcas.Domain.Models.Estudo_Viabilidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Clienteid")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Data_conclusao")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("Data_criacao")
                        .HasColumnType("time");

                    b.Property<int>("Empresaid")
                        .HasColumnType("int");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ordem_servico_id")
                        .HasColumnType("int");

                    b.Property<short>("Parecer")
                        .HasColumnType("smallint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<short>("Status_proposta_id")
                        .HasColumnType("smallint");

                    b.Property<int>("Usuario_criador_id")
                        .HasColumnType("int");

                    b.Property<int>("Usuario_responsavel_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Clienteid");

                    b.HasIndex("Empresaid");

                    b.HasIndex("Ordem_servico_id");

                    b.HasIndex("Status_proposta_id");

                    b.HasIndex("Usuario_criador_id");

                    b.HasIndex("Usuario_responsavel_id");

                    b.ToTable("Estudo_Viabilidade");
                });

            modelBuilder.Entity("Sistemarcas.Domain.Models.Estudo_Viabilidade_Marcas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Estudo_viabilidade_id")
                        .HasColumnType("int");

                    b.Property<string>("Marca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Segmento")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Estudo_viabilidade_id");

                    b.ToTable("Estudo_Viabilidade_Marcas");
                });

            modelBuilder.Entity("Sistemarcas.Domain.Models.Estudo_Viabilidade_Marcas_Itens", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Classe_item_id")
                        .HasColumnType("int");

                    b.Property<int>("Estudo_viabilidade_marca_id")
                        .HasColumnType("int");

                    b.Property<bool>("Gerada_os")
                        .HasColumnType("bit");

                    b.Property<short>("Parecer")
                        .HasColumnType("smallint");

                    b.Property<string>("Texto_livre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Classe_item_id");

                    b.HasIndex("Estudo_viabilidade_marca_id");

                    b.ToTable("Estudo_Viabilidade_Marcas_Itens");
                });

            modelBuilder.Entity("Sistemarcas.Domain.Models.FormasPagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FormasPagamento");
                });

            modelBuilder.Entity("Sistemarcas.Domain.Models.GruposPermissoes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GruposPermissoes");
                });

            modelBuilder.Entity("Sistemarcas.Domain.Models.GruposPermissoesDetalhes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Grupopermissaoid")
                        .HasColumnType("int");

                    b.Property<int>("Permissaoid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("GruposPermissoesDetalhes");
                });

            modelBuilder.Entity("Sistemarcas.Domain.Models.Instituicoes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Pessoa_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Pessoa_id");

                    b.ToTable("Instituicoes");
                });

            modelBuilder.Entity("Sistemarcas.Domain.Models.LogErros", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Datahora")
                        .HasColumnType("datetime2");

                    b.Property<int>("Empresaid")
                        .HasColumnType("int");

                    b.Property<string>("Mensagem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modulo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Usuarioid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("LogErros");
                });

            modelBuilder.Entity("Sistemarcas.Domain.Models.Log_OrdemServico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Acao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ordemservicoid")
                        .HasColumnType("int");

                    b.Property<short>("Statusid")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("Log_OrdemServico");
                });

            modelBuilder.Entity("Sistemarcas.Domain.Models.OpcoesGerais", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Caminhoarquivosportal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Emailsdadosportal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Emailsgerenciais")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Emailsloginportal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Emailssenhaportal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Keygoogle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Portaemail")
                        .HasColumnType("int");

                    b.Property<string>("Senhaemail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Smtpemail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Sslemail")
                        .HasColumnType("bit");

                    b.Property<string>("Usuarioemail")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OpcoesGerais");
                });

            modelBuilder.Entity("Sistemarcas.Domain.Models.OrdemServico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Calcularprazoservicos")
                        .HasColumnType("bit");

                    b.Property<int>("Clienteid")
                        .HasColumnType("int");

                    b.Property<int>("Contaid")
                        .HasColumnType("int");

                    b.Property<int>("Convenioid")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Dataautorizacao")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("Datahora")
                        .HasColumnType("time");

                    b.Property<int>("Despachoid")
                        .HasColumnType("int");

                    b.Property<int>("Empresaid")
                        .HasColumnType("int");

                    b.Property<bool>("Geradoautomatico")
                        .HasColumnType("bit");

                    b.Property<bool>("Gerarnfe")
                        .HasColumnType("bit");

                    b.Property<string>("Numeropedido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Pessoa_vendedor_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Prazoautorizacao")
                        .HasColumnType("datetime2");

                    b.Property<short>("Prioridade")
                        .HasColumnType("smallint");

                    b.Property<short>("Situacao")
                        .HasColumnType("smallint");

                    b.Property<int>("Tipopedido")
                        .HasColumnType("int");

                    b.Property<decimal>("Valordesconto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Valorliquido")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Valorpedido")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Valorpermuta")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Vendedorid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("Sistemarcas.Domain.Models.OrdemServico_Patentes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ordemservicoid")
                        .HasColumnType("int");

                    b.Property<DateTime>("Prazoautorizacao")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Ordemservicoid");

                    b.ToTable("OrdemServico_Patentes");
                });

            modelBuilder.Entity("Sistemarcas.Domain.Models.OrdemServico_Regras", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Despachoid")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Peticaoid_extraordinario")
                        .HasColumnType("int");

                    b.Property<int>("Peticaoid_extraordinario2")
                        .HasColumnType("int");

                    b.Property<int>("Peticaoid_ordinario")
                        .HasColumnType("int");

                    b.Property<int>("Peticaoid_ordinario2")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Despachoid");

                    b.ToTable("OrdemServico_Regras");
                });

            modelBuilder.Entity("Sistemarcas.Domain.Models.Ordem_Servico_Colaboradores", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Ordem_servico_id")
                        .HasColumnType("int");

                    b.Property<int>("Pessoa_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Ordem_servico_id");

                    b.HasIndex("Pessoa_id");

                    b.ToTable("Ordem_Servico_Colaboradores");
                });

            modelBuilder.Entity("Sistemarcas.Domain.Models.Ordem_Servico_Comissoes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Ordem_servico_id")
                        .HasColumnType("int");

                    b.Property<int>("Pessoa_id")
                        .HasColumnType("int");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Ordem_servico_id");

                    b.HasIndex("Pessoa_id");

                    b.ToTable("Ordem_Servico_Comissoes");
                });

            modelBuilder.Entity("Sistemarcas.Domain.Models.Paises", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Paises");
                });

            modelBuilder.Entity("Sistemarcas.Domain.Models.Pedidos_Anexos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nomearquivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pedidos_Anexos");
                });

            modelBuilder.Entity("Sistemarcas.Domain.Models.Permissoes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<short>("Codigopermissao")
                        .HasColumnType("smallint");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("Ordem")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("Permissoes");
                });

            modelBuilder.Entity("Sistemarcas.Domain.Models.Pessoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bairro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Celular")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Cidadeid")
                        .HasColumnType("int");

                    b.Property<string>("Cnpj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Complemento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cpf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Datanascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Documentoprofissional")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Endereco")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("Estadocivilid")
                        .HasColumnType("smallint");

                    b.Property<string>("Fantasia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inscricao_estadual")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Internacional")
                        .HasColumnType("bit");

                    b.Property<string>("Nacionalidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naturalidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Primeiroacessoportal")
                        .HasColumnType("bit");

                    b.Property<string>("Profissao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Razao_social")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senhaportal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sexo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Pessoa");
                });

            modelBuilder.Entity("Sistemarcas.Domain.Models.Pessoa_Comissao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Pessoa_id")
                        .HasColumnType("int");

                    b.Property<int>("Tipo_despacho_id")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Pessoa_id");

                    b.HasIndex("Tipo_despacho_id");

                    b.ToTable("Pessoa_Comissao");
                });

            modelBuilder.Entity("Sistemarcas.Domain.Models.Portes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Portes");
                });

            modelBuilder.Entity("Sistemarcas.Domain.Models.Processos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Clienteid")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data_ultimasituacao")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("Datacriacao")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("Datarenovacao")
                        .HasColumnType("time");

                    b.Property<int>("Empresaid")
                        .HasColumnType("int");

                    b.Property<string>("Numeroprocesso")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Pedidoid")
                        .HasColumnType("int");

                    b.Property<bool>("ProcessoExterno")
                        .HasColumnType("bit");

                    b.Property<int>("Processofilhoid")
                        .HasColumnType("int");

                    b.Property<int>("Processosituacaoid")
                        .HasColumnType("int");

                    b.Property<short>("Servicoid")
                        .HasColumnType("smallint");

                    b.Property<int>("Situacaoregistroid")
                        .HasColumnType("int");

                    b.Property<short>("Tipo")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("Pedidoid");

                    b.HasIndex("Processofilhoid");

                    b.HasIndex("Processosituacaoid");

                    b.HasIndex("Servicoid");

                    b.ToTable("Processos");
                });

            modelBuilder.Entity("Sistemarcas.Domain.Models.Processos_Log_Situacoes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<TimeSpan>("Data")
                        .HasColumnType("time");

                    b.Property<int>("Processoid")
                        .HasColumnType("int");

                    b.Property<int>("Situacaoid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Processos_Log_Situacoes");
                });

            modelBuilder.Entity("Sistemarcas.Domain.Models.Processos_Marcas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Classeid")
                        .HasColumnType("int");

                    b.Property<string>("Conclusao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Datavigencia")
                        .HasColumnType("datetime2");

                    b.Property<string>("Elementonominativo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fimprazoextraordinario")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Fimprazoordinario")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Inicioprazoextraordinario")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Inicioprazoordinario")
                        .HasColumnType("datetime2");

                    b.Property<string>("Logomarca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("Logosituacao")
                        .HasColumnType("smallint");

                    b.Property<int>("Processoid")
                        .HasColumnType("int");

                    b.Property<string>("Resultados")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Situacaoespecial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("Situacaoid")
                        .HasColumnType("smallint");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<short>("Tipo")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("Classeid");

                    b.HasIndex("Processoid");

                    b.ToTable("Processos_Marcas");
                });

            modelBuilder.Entity("Sistemarcas.Domain.Models.Processos_Marcas_Classes_Itens", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Classeitemid")
                        .HasColumnType("int");

                    b.Property<int>("Processomarcaid")
                        .HasColumnType("int");

                    b.Property<string>("Textolivre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Classeitemid");

                    b.HasIndex("Processomarcaid");

                    b.ToTable("Processos_Marcas_Classes_Itens");
                });

            modelBuilder.Entity("Sistemarcas.Domain.Models.Processos_Movimentacoes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<TimeSpan>("Datahora")
                        .HasColumnType("time");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Processopeticaoid")
                        .HasColumnType("int");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<int>("Tarefaid")
                        .HasColumnType("int");

                    b.Property<short>("Tipo")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("Processopeticaoid");

                    b.HasIndex("Tarefaid");

                    b.ToTable("Processos_Movimentacoes");
                });

            modelBuilder.Entity("Sistemarcas.Domain.Models.Processos_Peticoes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Custo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<TimeSpan>("Datacriacao")
                        .HasColumnType("time");

                    b.Property<DateTime>("Dataprazoextraordinario")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Dataprazoordinario")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("Dataprotocolo")
                        .HasColumnType("time");

                    b.Property<int>("Despachodetalheid")
                        .HasColumnType("int");

                    b.Property<string>("Nossonumero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numeroprocesso")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numeroprotocolo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Pedidoid")
                        .HasColumnType("int");

                    b.Property<int>("Prazoextraordinario")
                        .HasColumnType("int");

                    b.Property<int>("Prazoordinario")
                        .HasColumnType("int");

                    b.Property<int>("Processoid")
                        .HasColumnType("int");

                    b.Property<short>("Situacaopeticaoid")
                        .HasColumnType("smallint");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<string>("Texto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tipodespachoid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Pedidoid");

                    b.HasIndex("Processoid");

                    b.HasIndex("Tipodespachoid");

                    b.ToTable("Processos_Peticoes");
                });

            modelBuilder.Entity("Sistemarcas.Domain.Models.Processos_Servicos_Adicionais", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Processomarcaid")
                        .HasColumnType("int");

                    b.Property<short>("Servicoid")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("Processomarcaid");

                    b.HasIndex("Servicoid");

                    b.ToTable("Processos_Servicos_Adicionais");
                });

            modelBuilder.Entity("Sistemarcas.Domain.Models.Processos_Situacoes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<short>("Grupo")
                        .HasColumnType("smallint");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Processos_Situacoes");
                });

            modelBuilder.Entity("Sistemarcas.Domain.Models.Ramos_De_Atividade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ramos_De_Atividade");
                });

            modelBuilder.Entity("Sistemarcas.Domain.Models.Regras_Despachos_Fluxos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<short>("Regra_id")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("Regras_Despachos_Fluxos");
                });

            modelBuilder.Entity("Sistemarcas.Domain.Models.Regras_Despachos_Processos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<short>("Regra_id")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("Regras_Despachos_Processos");
                });

            modelBuilder.Entity("Sistemarcas.Domain.Models.Servicos", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<short>("Grupo")
                        .HasColumnType("smallint");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("Tipo")
                        .HasColumnType("smallint");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Servicos");
                });

            modelBuilder.Entity("Sistemarcas.Domain.Models.SituacoesRegistro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("Grupo")
                        .HasColumnType("smallint");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SituacoesRegistro");
                });

            modelBuilder.Entity("Sistemarcas.Domain.Models.SituacoesRegistro_Automatizacoes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Situacaoregistroid")
                        .HasColumnType("int");

                    b.Property<int>("Tipodespachoid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Situacaoregistroid");

                    b.HasIndex("Tipodespachoid");

                    b.ToTable("SituacoesRegistro_Automatizacoes");
                });

            modelBuilder.Entity("Sistemarcas.Domain.Models.Situacoes_Regras", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Condicao1_peticaoid")
                        .HasColumnType("int");

                    b.Property<int>("Condicao1_situacaoid")
                        .HasColumnType("int");

                    b.Property<int>("Condicao2_peticaoid")
                        .HasColumnType("int");

                    b.Property<int>("Condicao2_peticaoid2")
                        .HasColumnType("int");

                    b.Property<int>("Condicao2_situacaoid")
                        .HasColumnType("int");

                    b.Property<int>("Condicao3_aposdias_situacaoid")
                        .HasColumnType("int");

                    b.Property<int>("Condicao3_despachoid")
                        .HasColumnType("int");

                    b.Property<int>("Condicao3_dias")
                        .HasColumnType("int");

                    b.Property<int>("Condicao3_situacaoid")
                        .HasColumnType("int");

                    b.Property<int>("Condicao4_despachoid")
                        .HasColumnType("int");

                    b.Property<int>("Condicao4_situacaoid")
                        .HasColumnType("int");

                    b.Property<int>("Condicao5_situacaoid")
                        .HasColumnType("int");

                    b.Property<int>("Condicao6_situacaoid")
                        .HasColumnType("int");

                    b.Property<int>("Condicao7_peticaoid")
                        .HasColumnType("int");

                    b.Property<int>("Condicao7_peticaoid2")
                        .HasColumnType("int");

                    b.Property<int>("Condicao7_situacaoid")
                        .HasColumnType("int");

                    b.Property<int>("Condicao7_situacaoid2")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Usacondicao1")
                        .HasColumnType("bit");

                    b.Property<bool>("Usacondicao2")
                        .HasColumnType("bit");

                    b.Property<bool>("Usacondicao3")
                        .HasColumnType("bit");

                    b.Property<bool>("Usacondicao4")
                        .HasColumnType("bit");

                    b.Property<bool>("Usacondicao5")
                        .HasColumnType("bit");

                    b.Property<bool>("Usacondicao6")
                        .HasColumnType("bit");

                    b.Property<bool>("Usacondicao7")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Situacoes_Regras");
                });

            modelBuilder.Entity("Sistemarcas.Domain.Models.Status_Propostas", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<short>("Ativo")
                        .HasColumnType("smallint");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("Ordem")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("Status_Propostas");
                });

            modelBuilder.Entity("Sistemarcas.Domain.Models.Tarefas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Classeid")
                        .HasColumnType("int");

                    b.Property<int>("Clienteid")
                        .HasColumnType("int");

                    b.Property<string>("Codigotarefa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("Datainicio")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("Dataprevisaotermino")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("Datatermino")
                        .HasColumnType("time");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Despachoid")
                        .HasColumnType("int");

                    b.Property<int>("Empresaid")
                        .HasColumnType("int");

                    b.Property<int>("Financeiroid")
                        .HasColumnType("int");

                    b.Property<short>("Grupo")
                        .HasColumnType("smallint");

                    b.Property<int>("Pedidoid")
                        .HasColumnType("int");

                    b.Property<int>("Pendentetarefaid")
                        .HasColumnType("int");

                    b.Property<short>("Prioridade")
                        .HasColumnType("smallint");

                    b.Property<int>("Processo_peticaoid")
                        .HasColumnType("int");

                    b.Property<int>("Processoid")
                        .HasColumnType("int");

                    b.Property<short>("Servicoid")
                        .HasColumnType("smallint");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<short>("Tipotarefaid")
                        .HasColumnType("smallint");

                    b.Property<bool>("Transferencia")
                        .HasColumnType("bit");

                    b.Property<int>("Usuariocriadorid")
                        .HasColumnType("int");

                    b.Property<int?>("Usuarioid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Despachoid");

                    b.HasIndex("Pedidoid");

                    b.HasIndex("Servicoid");

                    b.HasIndex("Tipotarefaid");

                    b.HasIndex("Usuariocriadorid");

                    b.HasIndex("Usuarioid");

                    b.ToTable("Tarefas");
                });

            modelBuilder.Entity("Sistemarcas.Domain.Models.Tarefas_Escritorio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<TimeSpan>("Data_abertura")
                        .HasColumnType("time");

                    b.Property<DateTime>("Data_prazo")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("Prioridade")
                        .HasColumnType("smallint");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<int>("Usuarioresponsavelid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Usuarioresponsavelid");

                    b.ToTable("Tarefas_Escritorio");
                });

            modelBuilder.Entity("Sistemarcas.Domain.Models.Tarefas_Responsaveis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Tarefaid")
                        .HasColumnType("int");

                    b.Property<int>("Usuarioid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Tarefaid");

                    b.HasIndex("Usuarioid");

                    b.ToTable("Tarefas_Responsaveis");
                });

            modelBuilder.Entity("Sistemarcas.Domain.Models.TiposDespachos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Acao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Alterarsituacaoaposprazo")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Corfundoicone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Coricone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Custo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Custograndeporte")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("Grupo")
                        .HasColumnType("smallint");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nomeicone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Prazodiasalterarsituacao")
                        .HasColumnType("int");

                    b.Property<short>("Prazoextraordinario")
                        .HasColumnType("smallint");

                    b.Property<short>("Prazoordinario")
                        .HasColumnType("smallint");

                    b.Property<int>("Processosituacaoidautomatica")
                        .HasColumnType("int");

                    b.Property<int>("Processosituacaoidautorizado")
                        .HasColumnType("int");

                    b.Property<int>("Processosituacaoidincluir")
                        .HasColumnType("int");

                    b.Property<int>("Processosituacaoidnaoautorizado")
                        .HasColumnType("int");

                    b.Property<decimal>("Taxa_grande_porte")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Taxa_pequeno_porte")
                        .HasColumnType("decimal(18,2)");

                    b.Property<short>("Tipo")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("TiposDespachos");
                });

            modelBuilder.Entity("Sistemarcas.Domain.Models.TiposTarefas", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TiposTarefas");
                });

            modelBuilder.Entity("Sistemarcas.Domain.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<TimeSpan>("Cadastradoem")
                        .HasColumnType("time");

                    b.Property<long>("Cadastradopor")
                        .HasColumnType("bigint");

                    b.Property<string>("Login")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("Modificadoem")
                        .HasColumnType("time");

                    b.Property<long>("Modificadopor")
                        .HasColumnType("bigint");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Pessoa_id")
                        .HasColumnType("int");

                    b.Property<string>("Senha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("Tipo")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("Pessoa_id");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("Sistemarcas.Domain.Models.UsuarioPermissao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<TimeSpan>("Cadastradoem")
                        .HasColumnType("time");

                    b.Property<long>("Cadastradopor")
                        .HasColumnType("bigint");

                    b.Property<int>("Identidade")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Modificadoem")
                        .HasColumnType("time");

                    b.Property<long>("Modificadopor")
                        .HasColumnType("bigint");

                    b.Property<int>("Moduloid")
                        .HasColumnType("int");

                    b.Property<int>("Permissaoid")
                        .HasColumnType("int");

                    b.Property<int>("Usuarioid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UsuarioPermissao");
                });

            modelBuilder.Entity("Sistemarcas.Domain.Models.Vendedores", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Pessoa_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Pessoa_id");

                    b.ToTable("Vendedores");
                });

            modelBuilder.Entity("Sistemarcas.Domain.Models.Cidades", b =>
                {
                    b.HasOne("Sistemarcas.Domain.Models.Estados", "Estado")
                        .WithMany()
                        .HasForeignKey("Estadoid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("Sistemarcas.Domain.Models.Classes_Itens", b =>
                {
                    b.HasOne("Sistemarcas.Domain.Models.Classes", "Classes")
                        .WithMany()
                        .HasForeignKey("Classeid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Classes");
                });

            modelBuilder.Entity("Sistemarcas.Domain.Models.ClientesEmpresas", b =>
                {
                    b.HasOne("Sistemarcas.Domain.Models.Cargos", "Cargo")
                        .WithMany()
                        .HasForeignKey("Cargoid")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sistemarcas.Domain.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("Clienteid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sistemarcas.Domain.Models.Empresas", "Empresa")
                        .WithMany()
                        .HasForeignKey("Empresaid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cargo");

                    b.Navigation("Cliente");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("Sistemarcas.Domain.Models.Correspondentes", b =>
                {
                    b.HasOne("Sistemarcas.Domain.Models.Pessoa", "Pessoa")
                        .WithMany()
                        .HasForeignKey("Pessoa_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("Sistemarcas.Domain.Models.Despachos_Detalhes", b =>
                {
                    b.HasOne("Sistemarcas.Domain.Models.Despachos", "Despacho")
                        .WithMany()
                        .HasForeignKey("Despachoid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sistemarcas.Domain.Models.Processos", "Processo")
                        .WithMany()
                        .HasForeignKey("Processoid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sistemarcas.Domain.Models.TiposDespachos", "TipoDespacho")
                        .WithMany()
                        .HasForeignKey("Tipodespachoid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Despacho");

                    b.Navigation("Processo");

                    b.Navigation("TipoDespacho");
                });

            modelBuilder.Entity("Sistemarcas.Domain.Models.Empresas_Classes", b =>
                {
                    b.HasOne("Sistemarcas.Domain.Models.Classes_Itens", "ClasseItem")
                        .WithMany()
                        .HasForeignKey("Classeitemid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sistemarcas.Domain.Models.Empresas", "Empresa")
                        .WithMany()
                        .HasForeignKey("Empresaid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClasseItem");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("Sistemarcas.Domain.Models.Empresas_Cnaes", b =>
                {
                    b.HasOne("Sistemarcas.Domain.Models.Cnaes", "Cnae")
                        .WithMany()
                        .HasForeignKey("Cnaeid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sistemarcas.Domain.Models.Empresas", "Empresa")
                        .WithMany()
                        .HasForeignKey("Empresaid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cnae");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("Sistemarcas.Domain.Models.Estados", b =>
                {
                    b.HasOne("Sistemarcas.Domain.Models.Paises", "Pais")
                        .WithMany()
                        .HasForeignKey("Paisid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("Sistemarcas.Domain.Models.Estudo_Viabilidade", b =>
                {
                    b.HasOne("Sistemarcas.Domain.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("Clienteid")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sistemarcas.Domain.Models.Empresas", "Empresa")
                        .WithMany()
                        .HasForeignKey("Empresaid")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sistemarcas.Domain.Models.OrdemServico", "OrdemServico")
                        .WithMany()
                        .HasForeignKey("Ordem_servico_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sistemarcas.Domain.Models.Status_Propostas", "StatusProposta")
                        .WithMany()
                        .HasForeignKey("Status_proposta_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sistemarcas.Domain.Models.Usuario", "UsuarioCriador")
                        .WithMany()
                        .HasForeignKey("Usuario_criador_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sistemarcas.Domain.Models.Usuario", "UsuarioResponsavel")
                        .WithMany()
                        .HasForeignKey("Usuario_responsavel_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cliente");

                    b.Navigation("Empresa");

                    b.Navigation("OrdemServico");

                    b.Navigation("StatusProposta");

                    b.Navigation("UsuarioCriador");

                    b.Navigation("UsuarioResponsavel");
                });

            modelBuilder.Entity("Sistemarcas.Domain.Models.Estudo_Viabilidade_Marcas", b =>
                {
                    b.HasOne("Sistemarcas.Domain.Models.Estudo_Viabilidade", "EstudoViabilidade")
                        .WithMany()
                        .HasForeignKey("Estudo_viabilidade_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EstudoViabilidade");
                });

            modelBuilder.Entity("Sistemarcas.Domain.Models.Estudo_Viabilidade_Marcas_Itens", b =>
                {
                    b.HasOne("Sistemarcas.Domain.Models.Classes_Itens", "ClasseItem")
                        .WithMany()
                        .HasForeignKey("Classe_item_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sistemarcas.Domain.Models.Estudo_Viabilidade_Marcas", "EstudoViabilidadeMarca")
                        .WithMany()
                        .HasForeignKey("Estudo_viabilidade_marca_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClasseItem");

                    b.Navigation("EstudoViabilidadeMarca");
                });

            modelBuilder.Entity("Sistemarcas.Domain.Models.Instituicoes", b =>
                {
                    b.HasOne("Sistemarcas.Domain.Models.Pessoa", "Pessoa")
                        .WithMany()
                        .HasForeignKey("Pessoa_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("Sistemarcas.Domain.Models.OrdemServico_Patentes", b =>
                {
                    b.HasOne("Sistemarcas.Domain.Models.OrdemServico", "OrdemServico")
                        .WithMany()
                        .HasForeignKey("Ordemservicoid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrdemServico");
                });

            modelBuilder.Entity("Sistemarcas.Domain.Models.OrdemServico_Regras", b =>
                {
                    b.HasOne("Sistemarcas.Domain.Models.Despachos", "Despacho")
                        .WithMany()
                        .HasForeignKey("Despachoid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Despacho");
                });

            modelBuilder.Entity("Sistemarcas.Domain.Models.Ordem_Servico_Colaboradores", b =>
                {
                    b.HasOne("Sistemarcas.Domain.Models.OrdemServico", "OrdemServico")
                        .WithMany()
                        .HasForeignKey("Ordem_servico_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sistemarcas.Domain.Models.Pessoa", "Pessoa")
                        .WithMany()
                        .HasForeignKey("Pessoa_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrdemServico");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("Sistemarcas.Domain.Models.Ordem_Servico_Comissoes", b =>
                {
                    b.HasOne("Sistemarcas.Domain.Models.OrdemServico", "OrdemServico")
                        .WithMany()
                        .HasForeignKey("Ordem_servico_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sistemarcas.Domain.Models.Pessoa", "Pessoa")
                        .WithMany()
                        .HasForeignKey("Pessoa_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrdemServico");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("Sistemarcas.Domain.Models.Pessoa_Comissao", b =>
                {
                    b.HasOne("Sistemarcas.Domain.Models.Pessoa", "Pessoa")
                        .WithMany()
                        .HasForeignKey("Pessoa_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sistemarcas.Domain.Models.TiposDespachos", "TipoDespacho")
                        .WithMany()
                        .HasForeignKey("Tipo_despacho_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pessoa");

                    b.Navigation("TipoDespacho");
                });

            modelBuilder.Entity("Sistemarcas.Domain.Models.Processos", b =>
                {
                    b.HasOne("Sistemarcas.Domain.Models.OrdemServico", "OrdemServico")
                        .WithMany()
                        .HasForeignKey("Pedidoid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sistemarcas.Domain.Models.Processos_Marcas", "ProcessoFilho")
                        .WithMany()
                        .HasForeignKey("Processofilhoid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sistemarcas.Domain.Models.Processos_Situacoes", "ProcessoSituacao")
                        .WithMany()
                        .HasForeignKey("Processosituacaoid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sistemarcas.Domain.Models.Servicos", "Servico")
                        .WithMany()
                        .HasForeignKey("Servicoid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrdemServico");

                    b.Navigation("ProcessoFilho");

                    b.Navigation("ProcessoSituacao");

                    b.Navigation("Servico");
                });

            modelBuilder.Entity("Sistemarcas.Domain.Models.Processos_Marcas", b =>
                {
                    b.HasOne("Sistemarcas.Domain.Models.Classes", "Classe")
                        .WithMany()
                        .HasForeignKey("Classeid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sistemarcas.Domain.Models.Processos", "Processo")
                        .WithMany()
                        .HasForeignKey("Processoid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classe");

                    b.Navigation("Processo");
                });

            modelBuilder.Entity("Sistemarcas.Domain.Models.Processos_Marcas_Classes_Itens", b =>
                {
                    b.HasOne("Sistemarcas.Domain.Models.Classes_Itens", "ClasseItem")
                        .WithMany()
                        .HasForeignKey("Classeitemid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sistemarcas.Domain.Models.Processos_Marcas", "ProcessoMarca")
                        .WithMany()
                        .HasForeignKey("Processomarcaid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClasseItem");

                    b.Navigation("ProcessoMarca");
                });

            modelBuilder.Entity("Sistemarcas.Domain.Models.Processos_Movimentacoes", b =>
                {
                    b.HasOne("Sistemarcas.Domain.Models.Processos_Peticoes", "ProcessoPeticao")
                        .WithMany()
                        .HasForeignKey("Processopeticaoid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sistemarcas.Domain.Models.Tarefas", "Tarefa")
                        .WithMany()
                        .HasForeignKey("Tarefaid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcessoPeticao");

                    b.Navigation("Tarefa");
                });

            modelBuilder.Entity("Sistemarcas.Domain.Models.Processos_Peticoes", b =>
                {
                    b.HasOne("Sistemarcas.Domain.Models.OrdemServico", "OrdemServico")
                        .WithMany()
                        .HasForeignKey("Pedidoid")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sistemarcas.Domain.Models.Processos", "Processo")
                        .WithMany()
                        .HasForeignKey("Processoid")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sistemarcas.Domain.Models.TiposDespachos", "TipoDespacho")
                        .WithMany()
                        .HasForeignKey("Tipodespachoid")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("OrdemServico");

                    b.Navigation("Processo");

                    b.Navigation("TipoDespacho");
                });

            modelBuilder.Entity("Sistemarcas.Domain.Models.Processos_Servicos_Adicionais", b =>
                {
                    b.HasOne("Sistemarcas.Domain.Models.Processos_Marcas", "ProcessoMarca")
                        .WithMany()
                        .HasForeignKey("Processomarcaid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sistemarcas.Domain.Models.Servicos", "Servico")
                        .WithMany()
                        .HasForeignKey("Servicoid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProcessoMarca");

                    b.Navigation("Servico");
                });

            modelBuilder.Entity("Sistemarcas.Domain.Models.SituacoesRegistro_Automatizacoes", b =>
                {
                    b.HasOne("Sistemarcas.Domain.Models.SituacoesRegistro", "SituacoesRegistro")
                        .WithMany()
                        .HasForeignKey("Situacaoregistroid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sistemarcas.Domain.Models.TiposDespachos", "TiposDespachos")
                        .WithMany()
                        .HasForeignKey("Tipodespachoid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SituacoesRegistro");

                    b.Navigation("TiposDespachos");
                });

            modelBuilder.Entity("Sistemarcas.Domain.Models.Tarefas", b =>
                {
                    b.HasOne("Sistemarcas.Domain.Models.Despachos", "Despacho")
                        .WithMany()
                        .HasForeignKey("Despachoid");

                    b.HasOne("Sistemarcas.Domain.Models.OrdemServico", "OrdemServico")
                        .WithMany()
                        .HasForeignKey("Pedidoid");

                    b.HasOne("Sistemarcas.Domain.Models.Servicos", "Servico")
                        .WithMany()
                        .HasForeignKey("Servicoid");

                    b.HasOne("Sistemarcas.Domain.Models.TiposTarefas", "TipoTarefa")
                        .WithMany()
                        .HasForeignKey("Tipotarefaid");

                    b.HasOne("Sistemarcas.Domain.Models.Usuario", "UsuarioCriador")
                        .WithMany()
                        .HasForeignKey("Usuariocriadorid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sistemarcas.Domain.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("Usuarioid");

                    b.Navigation("Despacho");

                    b.Navigation("OrdemServico");

                    b.Navigation("Servico");

                    b.Navigation("TipoTarefa");

                    b.Navigation("Usuario");

                    b.Navigation("UsuarioCriador");
                });

            modelBuilder.Entity("Sistemarcas.Domain.Models.Tarefas_Escritorio", b =>
                {
                    b.HasOne("Sistemarcas.Domain.Models.Usuario", "UsuarioResponsavel")
                        .WithMany()
                        .HasForeignKey("Usuarioresponsavelid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UsuarioResponsavel");
                });

            modelBuilder.Entity("Sistemarcas.Domain.Models.Tarefas_Responsaveis", b =>
                {
                    b.HasOne("Sistemarcas.Domain.Models.Tarefas", "Tarefa")
                        .WithMany()
                        .HasForeignKey("Tarefaid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sistemarcas.Domain.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("Usuarioid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tarefa");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Sistemarcas.Domain.Models.Usuario", b =>
                {
                    b.HasOne("Sistemarcas.Domain.Models.Pessoa", "Pessoa")
                        .WithMany()
                        .HasForeignKey("Pessoa_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("Sistemarcas.Domain.Models.Vendedores", b =>
                {
                    b.HasOne("Sistemarcas.Domain.Models.Pessoa", "Pessoa")
                        .WithMany()
                        .HasForeignKey("Pessoa_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pessoa");
                });
#pragma warning restore 612, 618
        }
    }
}
